-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Chef CASCADE;
DROP TABLE IF EXISTS Recipe CASCADE;
DROP TABLE IF EXISTS Comment CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS RecipeIngredient CASCADE;
DROP TABLE IF EXISTS Keyword CASCADE;
DROP TABLE IF EXISTS RecipeKeyword CASCADE;
